project:
  type: website
  output-dir: docs

website:
  title: "Emily Mitchell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume.qmd 
      - text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

