project:
  type: website
  output-dir: docs

website:
  title: "Emily Mitchell"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - about.qmd
      - resume.qmd 
  sidebar:
    style: docked
    contents:
      - text: LinkedIn
        href: https://www.linkedin.com/in/emilymitchell8
      - text: Email
        href: mailto:ekmitch@colostate.edu
      - text: Github
        href: https://github.com/emilymitchell8
      
page-footer:
    left: "© 2025 Emily Mitchell"
    right: "[My GitHub](https://github.com/emilymitchell8)"

format:
  html:
    theme: custom.scss
    css: custom.scss
    toc: true

editor: visual

