project:
  type: website
  output-dir: docs

website:
  title: "Emily Mitchell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd 

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true

editor: visual

