project:
  type: website
  output-dir: docs

website:
  title: "Emily Mitchell"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - about.qmd
      - resume.qmd 
      
page-footer:
    left: "© 2025 Emily Mitchell"
    right: "[My GitHub](https://github.com/emilymitchell8)"

format:
  html:
    theme: custom.scss
    css: custom.scss
    toc: true

editor: visual

