project:
  type: website
  output-dir: docs

website:
  title: "Emily Mitchell"
  page-footer:
    left: "© 2025 Emily Mitchell"
    right: "[My GitHub](https://github.com/emilymitchell8)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd 

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true

editor: visual

